### ISSUE TITLE
OSX: Error: cannot open file: stew/bitops2

### ISSUE THREAD

**Issue by timotheecour** [status-im/nim-stint#103]
nim c -o:stintt -r stint.nim
/Users/timothee/git_clone/nim/temp/nim-stint/stint.nim(10, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/temp/nim-stint/stint/bitops2.nim(10, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/temp/nim-stint/stint/private/bitops2_priv.nim(10, 40) Error: cannot open file: stew/bitops2
  import  ./datatypes, ./conversion, stew/bitops2

**Comment by arnetheduck** [comment]
install dependencies?

**Comment by timotheecour** [comment]
occurred when running CI for important_packages on OSX.
I have a pending PR to fix it via s/false/true in:
`pkg "stint", true, "nim c -o:stintt -r stint.nim"`

**Comment by arnetheduck** [comment]
stint depends on stew - probably you had some old stew version installed, as nimble will reuse any random version it finds.
