### ISSUE TITLE
Implement modulo add, sub, mul, inverse, exp, square

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-stint#18]
The library is missing modulo operations which are key for crypto.

Additionally, a template/macro that can replace all operations by their modulo version would be nice:

```Nim
with_modulo(1234567):
  let a = u + v
  let b = exp(a)
  let c = a - b * b
```

Additionally, it might be interesting to look into how libdivide implements repeated divisions by the same divisor as it's 2x to 3x faster than assembly divide: https://github.com/ridiculousfish/libdivide#c-example

**Comment by debragail** [comment]
I wouldn’t look to libdivide I’d roll my own if I were you

**Comment by mratsim** [comment]
Yes, libdivide only support uint64 anyway. I need arbitrary power of 2 precision (uint256 and int256 for ethereum and uint2048 for bloom filters).

The core modulo operation is there: https://github.com/status-im/nim-mpint/blob/master/src/private/uint_div.nim#L284 but if you need to repeatedly divide by the same number apparently you can find a magic number that transforms division into simpler operations (shifts, multiplication ?).

**Comment by debragail** [comment]
I’m new to blockchain but I know ethereum and bloom, but not how you use modulo.  Can you maybe help me understand the scope of modulo function in this use case?  Anything to read up on go get me up to speed to make sure I understand the use case.

**Comment by mratsim** [comment]
Here are the uses cases

### Ethereum Virtual Machine

The ethereum VM requires `addmod` and `mulmod`

From https://github.com/djrtwo/evm-opcode-gas-costs/blob/master/opcode-gas-costs_EIP-150_revision-1e18248_2017-04-12.csv

| Value | Mnemonic   | Gas Used                                        | Subset  | Removed from stack | Added to stack | Notes                                             | Formula Notes                                                                                                                                             | 
|-------|------------|-------------------------------------------------|---------|--------------------|----------------|---------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------| 
| 0x00  | STOP       | 0                                               | zero    | 0                  | 0              | Halts execution.                                  |                                                                                                                                                           | 
| 0x01  | ADD        | 3                                               | verylow | 2                  | 1              | Addition operation                                |                                                                                                                                                           | 
| 0x02  | MUL        | 5                                               | low     | 2                  | 1              | Multiplication operation.                         |                                                                                                                                                           | 
| 0x03  | SUB        | 3                                               | verylow | 2                  | 1              | Subtraction operation.                            |                                                                                                                                                           | 
| 0x04  | DIV        | 5                                               | low     | 2                  | 1              | Integer division operation.                       |                                                                                                                                                           | 
| 0x05  | SDIV       | 5                                               | low     | 2                  | 1              | Signed integer division operation (truncated).    |                                                                                                                                                           | 
| 0x06  | MOD        | 5                                               | low     | 2                  | 1              | Modulo remainder operation                        |                                                                                                                                                           | 
| 0x07  | SMOD       | 5                                               | low     | 2                  | 1              | Signed modulo remainder operation.                |                                                                                                                                                           | 
| 0x08  | ADDMOD     | 8                                               | mid     | 3                  | 1              | Modulo addition operation.                        |                                                                                                                                                           | 
| 0x09  | MULMOD     | 8                                               | mid     | 3                  | 1              | Modulo multiplication operation.                  |                                                                                                                                                           | 

### Crypto

_Note that for crypto we use libsecp256k1 from bitcoin-core anyway._

In crypto, you often (always?) have to chain operations modulo a huge prime, if I take the example of Eth-keys and their ECDSA implementation - https://github.com/ethereum/eth-keys/blob/087c3cfd6d80d1bb39fddf475d8afec06ef088e3/eth_keys/backends/native/jacobian.py#L45-L48
we have the following:

```Python
def jacobian_add(p: Tuple[int, int, int],
                 q: Tuple[int, int, int]) -> Tuple[int, int, int]:
    if not p[1]:
        return q
    if not q[1]:
        return p
    U1 = (p[0] * q[2] ** 2) % P
    U2 = (q[0] * p[2] ** 2) % P
    S1 = (p[1] * q[2] ** 3) % P
    S2 = (q[1] * p[2] ** 3) % P
    if U1 == U2:
        if S1 != S2:
            return (0, 0, 1)
        return jacobian_double(p)
    H = U2 - U1
    R = S2 - S1
    H2 = (H * H) % P
    H3 = (H * H2) % P
    U1H2 = (U1 * H2) % P
    nx = (R ** 2 - H3 - 2 * U1H2) % P
    ny = (R * (U1H2 - nx) - S1 * H3) % P
    nz = (H * p[2] * q[2]) % P
    return (nx, ny, nz)
```

P is a cryptographic curve constant `SECPK1_P = 2**256 - 2**32 - 977`. If we take `U1 = (p[0] * q[2] ** 2) % P`, the actual way to compute it in a language without arbitrary precision (so multiplication and power can overflow) would be: `U1 = mulmod(p[0], squaremod(q[2], 2, P), P)`.

Using `U1 = ((p[0] mod P) * ((q[2] mod P) ** 2) mod P) mod P` is not enough to ensure no overflows but the implementation of `Mulmod` and `squaremod` should take care of that.

Furthermore, `mod` (and `div`) are very costly operations but since we know that the operands are all modulo the same number we can avoid it like I do in the modular arithmetic link in my previous post.
