### ISSUE TITLE
Add support for determinism in quicktest 

### ISSUE THREAD

**Issue by zah** [status-im/nim-stint#36]
After [discovering a problem](https://github.com/alehander42/nim-quicktest/issues/6) with depleting the random source used in the quicktest library, we've had an internal discussion concluding that we can benefit from the following new features in [quicktest](https://github.com/alehander42/nim-quicktest):

* Quicktest should use a private instance of a deterministic pseudo-random generator.
  The goal would be to isolate the randomness of the test cases generated by quicktest from any interference from the user. Otherwise, changing the body of a test may change the parameters generated by quicktest when a `random` call is added or removed from the test body. We recommend selecting a generator with high throughput.

* When a test fails, Quickcheck should report both the failing inputs (as it does now) and also the initial seed value, used to initialize the private random generator.

* There should be an environment variable, allowing the user to override the initial seed used by Quicktest. This will allow the user to repeat a failing test case with exactly the same parameters and it may also be used in CI environments, where test randomness between executions is less desired.

**Comment by alehander42** [comment]
@mratsim noticed that an iteration number would be also useful. Indeed, if yoy get an error on your 200000th run you might want to directly run only this iteration when you reproduce the bug: however this represents further limitations: you need a way to pass that info to quicktest: and if you need to pass seed + name test + iteration , that requires unique test name + one wouldn't change the test name while reproducing. is that a reasonable limitation?

**Comment by alehander42** [comment]
overally that still doesn't make sense.  quicktest would still need to execute the <iteration tests in order to keep it deterministic. one can somehow record the internal state of the rng before the failing iteration in order to start from there.

quicktest can also autogenerate a normal unittest with hardcoded values that one can reproduce until it's fixed, but this wouldn't work if you have additional rand values inside your test. (and it might break for some types)

**Comment by alehander42** [comment]
summary: iteration number would be quite useful as human readable metadata, but it's not so obvious if it would make sense to optimize the reproduction based on it

**Comment by zah** [comment]
Having the iteration number would allow quicktest to have "fast mode" where it only generates inputs until the desired iteration count is reached, without executing the actual tests.

All in all, I'm not sure how useful this would be, because per our Slack discussion, the developer can use the support for recording only the failed test cases to get even faster compile-test cycles. The initial seed is just a way to reproduce the results on another machine, so you can create bootstrap the other repro process.

**Comment by alehander42** [comment]
I thought the same, but then I thought about your argument that one can use e.g. rand also in his test logic. In this case you can't be sure that just generating input n times will lead to the same input in this iteration.

The problem with recording purely the failed test cases is that it can't account for using additional random generation in the test logic too. If one relaxes this requirement  there are two approaches: 
* marshalling failed inputs, which I use now, I am just not sure how robust is that (don't know how it's implemented)
* generating test with hardcoded inputs (which maybe wouldn't always work, e.g. you have object with private field and you don't know how to construct it, I suspect some super int values in stint might be similar: quicktest doesn't know about `'.i256` etc)

Anyway, those are some edge cases.

**Comment by alehander42** [comment]
One can have those fast-input-generation and generate/marshall-example options and use them in the majority of cases when there isn't some additional rand behavior

**Comment by zah** [comment]
Yes, I agree, this optimistic determinism is good enough :)

**Comment by alehander42** [comment]
Ok, initial version implemented in https://github.com/alehander42/nim-quicktest/commit/83a46937ed4adb3663641391826d9c809c48152c

Please note that it's an initial version: if there is something unclear or missing, don't hesitate to raise an issue

## errors

We display the generater args for an error and all errors in a test.
If you pass the `-f / --fail-fast` option we stop on the first error.
On an error you get the seed, test and iteration index
You can pass them again using an ENV variable: if the test has spaces
you can put it in "".


```bash
QUICKTEST_SEED = ..
# optionally:
QUICKTEST_TEST = ..
QUICKTEST_ITERATION = ..
```
or as args

```bash
./atest -f seed:.. test:.. iteration:..
```

If you pass only the seed, quicktest will reproduce all tests, if you pass
test and iteration too, it will only reproduce this iteration. This can break if you use additional
randomness inside the test: even something that depends on globalRNG.
Iteration arg requires test arg.

## overriding random generator

Quicktest uses QuickRNG which has `seed*: int64` and 

```bash
method randomize*(rng: QuickRNG, seed: int64) {.base.} =
  raise newException(ValueError, "not implemented")

method randomInt*(rng: QuickRNG, max: int): int {.base.} =
  raise newException(ValueError, "not implemented")
```

You need to inherit it and override the methods to implement your own generator.

You can `registerRNG(myRNG, seed=my)` and you can `registerRNG(defaultRNG, seed=my)` if
you want to just change the seed: currently it's generated based on time which is not perfect

**Comment by alehander42** [comment]
Currently quicktest uses the xorshift128+ from nim stdlib. The generation of initial seed needs some work: you can just pass your own custom seed using registerRNG(defaultRNG, your) , but probably we need a better default: currently it'based on time. The reseed for each test is based on the initial seed + hash of the repr of the args

**Comment by alehander42** [comment]
Also fixed dependencies in the next commit

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xd9a34693f4babdf8b50b4613647bcc8ff642fcdc516274d437f68d8aa4046743](https://etherscan.io/tx/0xd9a34693f4babdf8b50b4613647bcc8ff642fcdc516274d437f68d8aa4046743)

**Comment by zah** [comment]
@pablanopete, this bounty has been delivered. It's the 300 USD reward I told you about today in Slack. To be paid to 0xDf35522b002c09a60802439DBF98F1f4B2Ea6773

**Comment by zah** [comment]
The reward has been paid out.
