### ISSUE TITLE
Add a toUint proc

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-stint#58]
see https://github.com/status-im/nimbus/pull/86

**Comment by tersec** [comment]
An alternate approach which I've verified gets everything working, and in spirit (the code's not guaranteed to be especially pretty, e.g., hardcoding ``1 shl 31``) the right thing to do with signed int returns anyway:
```
diff --git a/stint/io.nim b/stint/io.nim
index ddec855..83ab210 100644
--- a/stint/io.nim
+++ b/stint/io.nim
@@ -75,7 +75,7 @@ func to*(x: SomeUnsignedInt, T: typedesc[StUint]): T =
 
 func toInt*(num: Stint or StUint): int {.inline.}=
   # Returns as int. Result is modulo 2^(sizeof(int)
-  num.data.least_significant_word.int
+  num.data.least_significant_word.int and ((1 shl 31) - 1)
 
 func readHexChar(c: char): int8 {.inline.}=
   ## Converts an hex char to an int
```

This, combined with https://github.com/status-im/nimbus/pull/94 gets every single test either not failing or skipped (some of the long benchmark-tests which hinder testing/iteration). The exact mechanism's not so important, but the basic point is that toInt running on the LSW or similar of a multiprecision integer should never return a bit pattern that, in signed interpretations, is negative. For example, max-clamping would probably work too, but this is cleaner to reason about and probably more efficient.

The tradeoff vs https://github.com/status-im/nim-stint/issues/58 is that this works on every existing ``foo.toInt`` reference in Nimbus, aside from being just conceptually more coherent than ``foo.toInt`` on a nonnegative stint returning a negative number, though both may be worthwhile.

**Comment by mratsim** [comment]
The proper way would be something similar to this to compute the `and mask` so that it works on 32 and 64-bit platforms:

https://github.com/status-im/nim-stint/blob/406f1aa317b0dac6ce1c8fe1f3aa1cb6e3603f10/stint/private/uint_div.nim#L131-L138

or

https://github.com/status-im/nim-stint/blob/406f1aa317b0dac6ce1c8fe1f3aa1cb6e3603f10/stint/private/uint_mul.nim#L19-L24

But `num.data.least_significant_word.int and ((1 shl 31) - 1)` strips the sign bit.

The following should stay correct:

```Nim
import stint

let x = -1.stint(Uint256)

let y = x.toInt

doAssert y == -1
```

If we need a non-standard nonnegative signed int, we can use `abs` or implement it as a helper in Nimbus.

**Comment by tersec** [comment]
The point is to strip the sign bit.

The Uint256 usage in Nimbus ensures that the putative negative values in the lower limbs of stuint representation are only ever artifacts, which then confuse bounds checks in Nimbus's VM. For Nimbus/Ethereum purposes, the st(u)int is used for storing $\mathbb{N}_{256}$ i.e. natural numbers less than 2^256 (slight Latex-ification applied):
> Throughout, we assume scalars are non-negative integers  and  thus  belong  to  the  set
$\mathbb{N}. ... and the set of all non-negative integers smaller than $2^{256}$ is named $\mathbb{N}_{256}$.

Negative `.toInt` values are, in this context, illusory artifacts of the Nim/general two's-complement-based integer type system.

This is, obviously, not necessarily true with signed stints, but even there, it's not clear to me why the least significant word/limb's signedness has anything to do with the stint's signedness, and therefore why it's particularly useful to preserve the sign bit in `toInt` here. The only case where it sort of accidentally produces meaningfully more correct semantics that I can figure out is where `.toInt` returns the entire bit pattern of a signed stint, and therefore the sign bit in the lower limb/word exactly aligns with the sign bit of the stint as a whole. For example:
```
  else: # We try to store an int64 in 2 x uint32 or 4 x uint16
  # For now we only support assignation from 64 to 2x32 bit
```
That is, for other cases, the underlying type's unsigned anyway.

Still, I will, instead, add a helper function to Nimbus, as you suggest.
