### ISSUE TITLE
UInt256 shr returns nonsensical values when shift amount too large

### ISSUE THREAD

**Issue by tersec** [status-im/nim-stint#65]
```
import stint

let a = fromHex(UInt256, "0x8000000000000000000000000000000000000000000000000000000000000000")
for i in 1..1025:
  echo i, ": ", a shr i
```
Compiled/run with `nim c -r --experimental:forLoopMacros test.nim`.

Operates plausibly correctly until `i == 255`, then repeats back through the `192..255` cases indefinitely, with a periodicity of 64.

**Comment by mratsim** [comment]
This is not a bug, C and C++ standard explicit says that this is undefined behaviour:

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2012/n3485.pdf

![2018-10-06_10-45-27](https://user-images.githubusercontent.com/22738317/46569415-f767a200-c954-11e8-90b0-e1bdaf8ff24d.png)

https://msdn.microsoft.com/en-us/library/336xbhcz.aspx#Anchor_5

![2018-10-06_10-45-57](https://user-images.githubusercontent.com/22738317/46569420-09e1db80-c955-11e8-945b-f53d27836ba0.png)

**Comment by tersec** [comment]
Fair enough. It comes up in the state tests, and I didn't want to add a downstream workaround if it was more appropriate for stint. However, it's just as easy/reasonable to ensure the EVM works within defined behavior.
