### ISSUE TITLE
Property-based testing, investigate div/mod/pow on uint256

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-stint#78]
See: https://github.com/status-im/nim-stint/pull/76#issuecomment-491510283

Related fixes:
- https://github.com/status-im/nim-stint/commit/0987af4467bcd940c978468dfaebb9d77aa13daa
- https://github.com/status-im/nim-stint/pull/32

**Comment by jangko** [comment]
ttmath div is buggy. need to pick other more reliable lib to test against.

the following case produce wrong result  using ttmath, correct for stint:
```
x: 3606134859212682416679510199016296690803894613795325832178297934841720078336
div
y: 1358491438598433054019441368095872029784757968073492320040002835314009702400
ttmath = 134154044
stint  = 2
```

This one will make ttmath hang.
```
x: 112625899297180263201643772698075858812317575960969609875119228611153627185151
div
y: 101770385727965230623924455673160029935643353476166713438443586995673962119168
```
