### ISSUE TITLE
0.20 compat - signed int SHR / right shift is broken

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-stint#81]
Signed integer right shift is broken on 0.20, can be reproduced by running the test suite with 0.20.

Unsigned integers are not affected

**Comment by mratsim** [comment]
There is a compat flag: `-d:nimOldShiftRight`

**Comment by jangko** [comment]
with nim 0.20.0, signed int `shr` behaves like `ashr`. we can either 'fix' signed int `shr` or rename `ashr` to `shr`.

**Comment by jangko** [comment]
@mratsim: can we remove `ashr`? there is no need for two identical operators with different name.

**Comment by mratsim** [comment]
Yes, no problem.

I think a warning in the operation description is needed for those still using 0.19.x and also replacing the `shr` test by `ashr`.
