### ISSUE TITLE
0.20 compat -- quicktest in test_int_bitwise trigger Nim VM bug/regression

### ISSUE THREAD

**Issue by jangko** [status-im/nim-stint#84]
error message when compiled with `nim -cpp -r tests/test_int_bitwise`:

```text
fatal.nim(39)            sysFatal
Error: unhandled exception: vm.nim(707, 16) `nfIsRef in regs[ra].node.flags`  [AssertionError]
```

with Nim 0.19.xx there is no error

**Comment by jangko** [comment]
if `let` at line 253 of quicktest.nim changed to `const`, it will cure the problem.
this is a nim compiler bug, nim-lang/nim#11903

**Comment by zah** [comment]
Can you file a PR? I'm sure @alehander42 will merge it quickly.

**Comment by jangko** [comment]
sure

**Comment by jangko** [comment]
turn out he already fixed it in his master branch. the one I'm using is what nimble installed -- from an outdated release package -- sigh.
closing this issue.
