### ISSUE TITLE
Improve compile time test coverage

### ISSUE THREAD

**Issue by jangko** [status-im/nim-stint#89]
This is related to #67 or part of it but specific to compile time.

for example a simple negative number const will crash Nim compiler v1.0.0

```Nim
const neg99 = -99.i256
```

if the time is come to migrate to Nim 1.xx, we need to make sure nothing escape our radar.
the simplest thing to do is copying runtime test and convert it to compile time.
but since the runtime test itself not complete, we can also port it back to runtime.

EDIT: related Nim issue nim-lang/Nim#12244

**Comment by arnetheduck** [comment]
https://github.com/status-im/nim-stew/blob/master/tests/test_endians2.nim#L34 is one way to do combined runtime+compiletime tests

**Comment by jangko** [comment]
thanks for the link

**Comment by jangko** [comment]
closing. fixed by #91
